comment_width = 110
max_width = 110
inline_attribute_width = 80
overflow_delimited_expr = true
newline_style = "Unix"
imports_granularity = "Crate"
reorder_imports = true
reorder_impl_items = true
format_code_in_doc_comments = true
wrap_comments = true
